version: "3.9"  # optional since v1.27.0
services:

  # Service
  backend:
    container_name: mft-receiver
    init: true
    tty: true
    restart: always
    build: .
    volumes:
      #              Host:container
      - .:/code
      #- ./Receiver/ubuntu/etc/shadow:/etc/
    command:  
      - /bin/sh
      - -c
      - |
        ls
        python3 manage.py sftpServer && python3 manage.py runserver 0.0.0.0:8080
    # Join network
    networks:
      sftp-receiver-network:
        ipv4_address: 19.4.0.35
 

# Network ++++++++++++++++++++++++++++++++++++++++++++
# https://docs.docker.com/compose/networking/
networks:
  sftp-receiver-network: # Create network
    driver: bridge # Mode
    ipam:
     config:
       - subnet: 19.4.0.0/16
         gateway: 19.4.0.1