version: "3.9"  # optional since v1.27.0
services:

  # Service
  backend:
    container_name: synchro-server
    init: true
    tty: true
    restart: always
    build: .
    volumes:
      # Host:container
      - .:/code
    command:  
      - /bin/sh
      - -c
      - |
        ls
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:${DOCKER_SYBCHRO_PORT}
    # Join network
    networks:
      synchro-network:
        ipv4_address: ${DOCKER_SYBCHRO_IP}
 

# Network ++++++++++++++++++++++++++++++++++++++++++++
# https://docs.docker.com/compose/networking/
networks:
  synchro-network: # Create network
    driver: bridge # Mode
    ipam:
     config:
       - subnet: ${DOCKER_SYBCHRO_NET_SUBNET}
         gateway: ${DOCKER_SYBCHRO_NET_GATEWAY}