version: "3.8"

services:

  backend:
    container_name: synchro-server
    tty: true
    build: .
    command: 
    - /bin/sh
    - -c
    - |
      python3 ./manage.py test

# Network ++++++++++++++++++++++++++++++++++++++++++++
# https://docs.docker.com/compose/networking/
networks:
  synchro-network: # Create network
    driver: bridge # Mode