name: Docker Test

on:
  push:
    branches:
          - 'master'
          - 'develop'

jobs:

  DockerImageTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code # checking our the code at current commit that triggers the workflow
      uses: actions/checkout@v2
    - name: Set ENV
      run: cp ./.env.example  ./.env
    - name: Build the docker-compose
      run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit